import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  dsa: [
    {
      type: 'category',
      label: '🕸 Graph',
      link: { type: 'doc', id: 'graph/graph-index' },
      items: [
        {
          type: 'category',
          label: 'Algorithms',
          collapsed: false,
          items: [
            'graph/dfs-bfs',
            'graph/union-find',
            'graph/topological-sort',
            'graph/dijkstra',
          ],
        },
        'graph/133-clone-graph',
        'graph/200-number-of-islands',
        'graph/207-course-schedule',
        'graph/210-course-schedule-ii',
        'graph/399-evaluate-division',
        'graph/417-pacific-atlantic-water-flow',
        'graph/547-number-of-provinces',
        'graph/684-redundant-connection',
        'graph/695-max-area-of-island',
        'graph/721-accounts-merge',
        'graph/841-keys-and-rooms',
        'graph/994-rotting-oranges',
        'graph/1091-shortest-path-in-binary-matrix',
        'graph/1466-reorder-routes-to-make-all-paths-lead-to-the-city-zero',
        'graph/1557-minimum-number-of-vertices-to-reach-all-nodes',
        'graph/1926-nearest-exit-from-entrance-in-maze',
        'graph/1971-find-if-path-exists-in-graph',
      ],
    },
    {
      type: 'category',
      label: '➕ Prefix Sum',
      link: { type: 'generated-index', slug: '/prefix-sum' },
      items: [
        'prefix-sum/238-product-of-array-except-self',
        'prefix-sum/724-find-pivot-index',
        'prefix-sum/1480-running-sum-of-1d-array',
        'prefix-sum/1732-find-the-highest-altitude',
      ],
    },
    {
      type: 'category',
      label: '🗂 Hash Map / Set',
      link: { type: 'generated-index', slug: '/hash-map-set' },
      items: [
        'hash-map-set/1-two-sum',
        'hash-map-set/13-roman-to-integer',
        'hash-map-set/36-valid-sudoku',
        'hash-map-set/49-group-anagrams',
        'hash-map-set/73-set-matrix-zeroes',
        'hash-map-set/242-valid-anagram',
        'hash-map-set/290-word-pattern',
        'hash-map-set/383-ransom-note',
        'hash-map-set/2215-find-the-difference-of-two-arrays',
      ],
    },
    {
      type: 'category',
      label: '↔️ Two Pointers',
      link: { type: 'generated-index', slug: '/two-pointers' },
      items: [
        'two-pointers/11-container-with-most-water',
        'two-pointers/1768-merge-strings-alternately',
        'two-pointers/26-remove-duplicates-from-sorted-array',
        'two-pointers/28-find-the-index-of-the-first-occurrence-in-a-string',
        'two-pointers/125-valid-palindrome',
        'two-pointers/151-reverse-words-in-a-string',
        'two-pointers/189-rotate-array',
        'two-pointers/283-move-zeroes',
        'two-pointers/345-reverse-vowels-of-a-string',
      ],
    },
    {
      type: 'category',
      label: '🔍 Binary Search',
      link: { type: 'generated-index', slug: '/binary-search' },
      items: [
        'binary-search/34-find-first-and-last-position-of-element-in-sorted-array',
        'binary-search/162-find-peak-element',
        'binary-search/222-count-complete-tree-nodes',
        'binary-search/374-guess-number-higher-or-lower',
        'binary-search/704-binary-search',
        'binary-search/981-time-based-key-value-store',
        'binary-search/2300-successful-pairs-of-spells-and-potions',
      ],
    },
    {
      type: 'category',
      label: '🪟 Sliding Window',
      link: { type: 'generated-index', slug: '/sliding-window' },
      items: [
        'sliding-window/3-longest-substring-without-repeating-characters',
        'sliding-window/187-repeated-dna-sequences',
        'sliding-window/209-minimum-size-subarray-sum',
        'sliding-window/424-longest-repeating-character-replacement',
        'sliding-window/438-find-all-anagrams-in-a-string',
        'sliding-window/567-permutation-in-string',
        'sliding-window/643-maximum-average-subarray-i',
        'sliding-window/713-subarray-product-less-than-k',
        'sliding-window/1343-number-of-sub-arrays-of-size-k-and-average-greater-than-or-equal-to-threshold',
        'sliding-window/1456-maximum-number-of-vowels-in-a-substring-of-given-length',
      ],
    },
    {
      type: 'category',
      label: '🔢 Math',
      link: { type: 'generated-index', slug: '/math' },
      items: [
        'math/9-palindrome-number',
        'math/412-fizz-buzz',
        'math/1071-greatest-common-divisor-of-strings',
      ],
    },
    {
      type: 'category',
      label: '🔤 String',
      link: { type: 'generated-index', slug: '/string' },
      items: [
        'string/2490-circular-sentence',
        'string/3110-score-of-a-string',
      ],
    },
    {
      type: 'category',
      label: '🌳 Trie',
      link: { type: 'generated-index', slug: '/trie' },
      items: [
        'trie/14-longest-common-prefix',
        'trie/208-implement-trie-prefix-tree',
        'trie/211-design-add-and-search-words-data-structure',
        'trie/212-word-search-ii',
        'trie/648-replace-words',
        'trie/1268-search-suggestions-system',
      ],
    },
    {
      type: 'category',
      label: '🔗 Linked List',
      link: { type: 'generated-index', slug: '/linked-list' },
      items: [
        'linked-list/2-add-two-numbers',
        'linked-list/19-remove-nth-node-from-end-of-list',
        'linked-list/21-merge-two-sorted-lists',
        'linked-list/82-remove-duplicates-from-sorted-list-ii',
        'linked-list/83-remove-duplicates-from-sorted-list',
        'linked-list/92-reverse-linked-list-ii',
        'linked-list/114-flatten-binary-tree-to-linked-list',
        'linked-list/116-populating-next-right-pointers-in-each-node',
        'linked-list/138-copy-list-with-random-pointer',
        'linked-list/141-linked-list-cycle',
        'linked-list/146-lru-cache',
        'linked-list/160-intersection-of-two-linked-lists',
        'linked-list/203-remove-linked-list-elements',
        'linked-list/206-reverse-linked-list',
        'linked-list/234-palindrome-linked-list',
        'linked-list/237-delete-node-in-a-linked-list',
        'linked-list/328-odd-even-linked-list',
        'linked-list/622-design-circular-queue',
        'linked-list/705-design-hashset',
        'linked-list/706-design-hashmap',
        'linked-list/876-middle-of-the-linked-list',
        'linked-list/1669-merge-in-between-linked-lists',
        'linked-list/2095-delete-the-middle-node-of-a-linked-list',
        'linked-list/2130-maximum-twin-sum-of-a-linked-list',
        'linked-list/2181-merge-nodes-in-between-zeros',
        'linked-list/2487-remove-nodes-from-linked-list',
        'linked-list/2807-insert-greatest-common-divisors-in-linked-list',
      ],
    },
    {
      type: 'category',
      label: '📬 Queue',
      link: { type: 'generated-index', slug: '/queue' },
      items: [
        'queue/933-number-of-recent-calls',
      ],
    },
    {
      type: 'category',
      label: '🏔 Heap',
      link: { type: 'generated-index', slug: '/heap' },
      items: [
        'heap/215-kth-largest-element-in-an-array',
        'heap/2336-smallest-number-in-infinite-set',
        'heap/2542-maximum-subsequence-score',
        'heap/2558-take-gifts-from-the-richest-pile',
      ],
    },
    {
      type: 'category',
      label: '📊 Monotonic Stack',
      link: { type: 'generated-index', slug: '/monotonic-stack' },
      items: [
        'monotonic-stack/84-largest-rectangle-in-histogram',
        'monotonic-stack/496-next-greater-element-i',
        'monotonic-stack/739-daily-temperatures',
        'monotonic-stack/853-car-fleet',
        'monotonic-stack/901-online-stock-span',
        'monotonic-stack/1475-final-prices-with-a-special-discount-in-a-shop',
      ],
    },
    {
      type: 'category',
      label: '🔙 Backtracking',
      link: { type: 'generated-index', slug: '/backtracking' },
      items: [
        'backtracking/17-letter-combinations-of-a-phone-number',
        'backtracking/22-generate-parentheses',
        'backtracking/39-combination-sum',
        'backtracking/40-combination-sum-ii',
        'backtracking/46-permutations',
        'backtracking/47-permutations-ii',
        'backtracking/51-n-queens',
        'backtracking/78-subsets',
        'backtracking/79-word-search',
        'backtracking/113-path-sum-ii',
        'backtracking/131-palindrome-partitioning',
        'backtracking/216-combination-sum-iii',
        'backtracking/257-binary-tree-paths',
        'backtracking/784-letter-case-permutation',
        'backtracking/797-all-paths-from-source-to-target',
      ],
    },
    {
      type: 'category',
      label: '📚 Stack',
      link: { type: 'generated-index', slug: '/stack' },
      items: [
        'stack/20-valid-parentheses',
        'stack/71-simplify-path',
        'stack/394-decode-string',
        'stack/682-baseball-game',
        'stack/735-asteroid-collision',
        'stack/1047-remove-all-adjacent-duplicates-in-string',
        'stack/2390-removing-stars-from-a-string',
      ],
    },
    {
      type: 'category',
      label: '📈 Dynamic Programming (1D)',
      link: { type: 'generated-index', slug: '/dp-1d' },
      items: [
        'dp-1d/42-trapping-rain-water',
        'dp-1d/70-climbing-stairs',
        'dp-1d/118-pascals-triangle',
        'dp-1d/121-best-time-to-buy-and-sell-stock',
        'dp-1d/392-is-subsequence',
        'dp-1d/509-fibonacci-number',
        'dp-1d/1137-n-th-tribonacci-number',
        'dp-1d/2900-longest-unequal-adjacent-groups-subsequence-i',
      ],
    },
    {
      type: 'category',
      label: '🧩 Array',
      link: { type: 'generated-index', slug: '/array' },
      items: [
        'array/66-plus-one',
        'array/1295-find-numbers-with-even-number-of-digits',
        'array/1431-kids-with-the-greatest-number-of-candies',
        'array/1550-three-consecutive-odds',
        'array/1752-check-if-array-is-sorted-and-rotated',
        'array/1920-build-array-from-permutation',
        'array/2176-count-equal-and-divisible-pairs-in-an-array',
        'array/2942-find-words-containing-character',
        'array/3105-longest-strictly-increasing-or-strictly-decreasing-subarray',
        'array/3151-special-array-i',
        'array/3392-count-subarrays-of-length-three-with-a-condition',
      ],
    },
    {
      type: 'category',
      label: '🌲 Binary Tree',
      link: { type: 'generated-index', slug: '/binary-tree' },
      items: [
        'binary-tree/94-binary-tree-inorder-traversal',
        'binary-tree/100-same-tree',
        'binary-tree/101-symmetric-tree',
        'binary-tree/102-binary-tree-level-order-traversal',
        'binary-tree/104-maximum-depth-of-binary-tree',
        'binary-tree/105-construct-binary-tree-from-preorder-and-inorder-traversal',
        'binary-tree/110-balanced-binary-tree',
        'binary-tree/112-path-sum',
        'binary-tree/129-sum-root-to-leaf-numbers',
        'binary-tree/144-binary-tree-preorder-traversal',
        'binary-tree/145-binary-tree-postorder-traversal',
        'binary-tree/199-binary-tree-right-side-view',
        'binary-tree/226-invert-binary-tree',
        'binary-tree/236-lowest-common-ancestor-of-a-binary-tree',
        'binary-tree/515-find-largest-value-in-each-tree-row',
        'binary-tree/543-diameter-of-binary-tree',
        'binary-tree/572-subtree-of-another-tree',
        'binary-tree/617-merge-two-binary-trees',
        'binary-tree/637-average-of-levels-in-binary-tree',
        'binary-tree/872-leaf-similar-trees',
        'binary-tree/1161-maximum-level-sum-of-a-binary-tree',
        'binary-tree/1448-count-good-nodes-in-binary-tree',
      ],
    },
    {
      type: 'category',
      label: '🔎 Binary Search Tree',
      link: { type: 'generated-index', slug: '/binary-search-tree' },
      items: [
        'binary-search-tree/98-validate-binary-search-tree',
        'binary-search-tree/108-convert-sorted-array-to-binary-search-tree',
        'binary-search-tree/230-kth-smallest-element-in-a-bst',
        'binary-search-tree/450-delete-node-in-a-bst',
        'binary-search-tree/700-search-in-a-binary-search-tree',
      ],
    },
    {
      type: 'category',
      label: '🌿 Greedy',
      link: { type: 'generated-index', slug: '/greedy' },
      items: [
        'greedy/135-candy',
        'greedy/334-increasing-triplet-subsequence',
        'greedy/605-can-place-flowers',
      ],
    },
    {
      type: 'category',
      label: '🔢 Bit Manipulation',
      link: { type: 'generated-index', slug: '/bit-manipulation' },
      items: [
        'bit-manipulation/1342-number-of-steps-to-reduce-a-number-to-zero',
      ],
    },
    {
      type: 'category',
      label: '🗃 Matrix',
      link: { type: 'generated-index', slug: '/matrix' },
      items: [
        'matrix/1672-richest-customer-wealth',
      ],
    },
  ],
};

export default sidebars;
